services:

  # =========================
  # DATABASES
  # =========================

  basketdb:
    image: redis:alpine
    container_name: basketdb
    restart: always
    ports:
      - "6379:6379"

  orderdb:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: orderdb
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "StrongPassword123!"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql

  discountdb:
    image: postgres:17
    container_name: discountdb
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Password@1
      POSTGRES_DB: DiscountDb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  catalogdb:
    image: mongo:latest
    container_name: catalogdb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db


  # =========================
  # RABBITMQ
  # =========================

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s


  # =========================
  # PAYMENT API
  # =========================

  payment:
    image: payment
    build:
      context: .
      dockerfile: Services/Payment/Payment/Dockerfile
    container_name: payment
    restart: on-failure
    ports:
      - "8010:8080"
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      EventBusSettings__HostAddress: amqp://guest:guest@rabbitmq:5672


  # =========================
  # ORDERING API
  # =========================

  ordering.api:
    image: ordering.api
    build:
      context: .
      dockerfile: Services/Ordering/Ordering.API/Dockerfile
    container_name: ordering.api
    restart: on-failure
    ports:
      - "8006:8080"
    depends_on:
      rabbitmq:
        condition: service_healthy
      orderdb:
        condition: service_started
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__OrderingConnectionString: "Server=orderdb,1433;Database=OrderDb;User Id=sa;Password=StrongPassword123!;TrustServerCertificate=True;Encrypt=False"
      EventBusSettings__HostAddress: "amqp://guest:guest@rabbitmq:5672"


  # =========================
  # CATALOG API
  # =========================

  catalog.api:
    image: catalog.api
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile
    container_name: catalog.api
    restart: on-failure
    ports:
      - "8080:8080"
    depends_on:
      catalogdb:
        condition: service_started
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__CatalogConnectionString: "mongodb://catalogdb:27017"


  # =========================
  # BASKET API
  # =========================

  basket.api:
    image: basket.api
    build:
      context: .
      dockerfile: Services/Basket/Basket.API/Dockerfile
    container_name: basket.api
    restart: on-failure
    ports:
      - "8003:8080"
    depends_on:
      rabbitmq:
        condition: service_healthy
      basketdb:
        condition: service_started
      discount.api:
        condition: service_started
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      CacheSettings__ConnectionString: "basketdb:6379"
      GrpcSettings__DiscountUrl: "http://discount.api:8080"
      EventBusSettings__HostAddress: "amqp://guest:guest@rabbitmq:5672"


  # =========================
  # DISCOUNT API
  # =========================

  discount.api:
    image: discount.api
    build:
      context: .
      dockerfile: Services/Discount/Discount.API/Dockerfile
    container_name: discount.api
    restart: on-failure
    ports:
      - "8004:8080"
    depends_on:
      discountdb:
        condition: service_started
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DiscountConnectionString: "Host=discountdb;Port=5432;Database=DiscountDb;Username=admin;Password=Password@1"


# =========================
# VOLUMES
# =========================

volumes:
  mongo_data:
  postgres_data:
  sqlserver_data: